repos:
  - repo: local
    hooks:
      - id: check-commit-message
        name: Check commit message format
        entry: python yana/.github/scripts/check_commit_message.py
        language: python
        stages: [commit-msg]