repos:
  - repo: local
    hooks:
      - id: check-commit-message
        name: Check commit message format
        entry: python check_commit_message.py
        language: system
        stages: [commit-msg]
