FROM python:3.12-alpine3.19

WORKDIR /app

COPY requirements.txt .

RUN apk add --no-cache --virtual .build-deps gcc musl-dev python3-dev libffi-dev openssl-dev
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN apk del .build-deps

COPY . .

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]