# Etapa 1: Builder
FROM python:3.12-alpine3.19 AS builder

WORKDIR /app

COPY requirements.txt .

# Actualiza pip e instala dependencias
RUN pip install --upgrade pip && \
  pip install -r requirements.txt --no-cache-dir

# Copia el resto del proyecto
COPY yana/. .

# Etapa 2: Imagen final
FROM gcr.io/distroless/python3

WORKDIR /app

# Copia las dependencias instaladas desde la etapa builder
COPY --from=builder /usr/local/lib/python3.12/site-packages/ /usr/lib/python3.12/
COPY --from=builder /app /app

ENV PYTHONUNBUFFERED=1 \
  PORT=8000

CMD ["manage.py", "runserver", "0.0.0.0:8000"]