# Generated by Django 5.2 on 2025-04-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_avatar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='unread_messages',
            field=models.BooleanField(default=False),
        ),
    ]
