# Generated by Django 5.1.7 on 2025-04-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
