# Generated by Django 5.1.7 on 2025-04-24 16:54

import apps.emotions.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0002_alter_sharedemotion_latitude_alter_sharedemotion_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedemotion',
            name='latitude',
            field=apps.emotions.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='sharedemotion',
            name='longitude',
            field=apps.emotions.fields.EncryptedTextField(),
        ),
    ]
