# Generated by Django 5.1.7 on 2025-04-07 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0002_alter_emotion_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotion',
            name='image',
        ),
    ]
