# Generated by Django 5.1.7 on 2025-04-09 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0002_useremotion_latitude_useremotion_longitude_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserEmotion',
        ),
    ]
