# Generated by Django 5.1.7 on 2025-04-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0002_alter_emotion_name_useremotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='emotions/'),
        ),
    ]
