# Generated by Django 5.1.7 on 2025-04-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0003_emotion_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotion',
            name='image',
        ),
        migrations.AddField(
            model_name='useremotion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='emotions/'),
        ),
    ]
