# Generated by Django 5.1.7 on 2025-04-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0004_remove_emotion_image_useremotion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='emotions/'),
        ),
        migrations.DeleteModel(
            name='UserEmotion',
        ),
    ]
