# Generated by Django 5.2 on 2025-04-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_helpresource_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpresource',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='helpresource',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
