name: GCP Production CI/CD Pipeline

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - cicd/pipeline
  workflow_dispatch:

env:
  PROJECT_ID: "training-batch-05"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: false
          PYTHONPATH: /app:/app/yana:/usr/local/lib/python3.11/site-packages
        run: |
          cd yana
          python manage.py test apps.emotions.tests apps.message.tests --verbose

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-east1-docker.pkg.dev
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image to Artifact Registry
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            us-east1-docker.pkg.dev/${{ env.PROJECT_ID }}/yana-back/prod:latest
          cache-from: type=registry,ref=us-east1-docker.pkg.dev/${{ env.PROJECT_ID }}/yana-back/buildcache
          cache-to: type=registry,ref=us-east1-docker.pkg.dev/${{ env.PROJECT_ID }}/yana-back/buildcache,mode=max

  deploy-to-GCP:
    runs-on: [self-hosted, linux, prod, GCP]
    needs: build-and-push-image
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-east1-docker.pkg.dev --quiet

      - name: Pull the latest image
        run: |
          docker pull us-east1-docker.pkg.dev/${{ env.PROJECT_ID }}/yana-back/prod:latest

      - name: Stop and remove existing container
        run: |
          docker stop yana-back || true
          docker rm yana-back || true

      - name: Deploy to Cloud Run
        run: |
          docker run -d \
            -p 8000:8000 \
            -e PYTHONUNBUFFERED=1 \
            -e PORT=8000 \
            -e PYTHONPATH=/app:/app/yana:/usr/local/lib/python3.11/site-packages \
            -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            -e SECRET_KEY="${{ secrets.SECRET_KEY }}" \
            -e DEBUG=false \
            --name yana-back \
            --restart=unless-stopped \
            us-east1-docker.pkg.dev/${{ env.PROJECT_ID }}/yana-back/prod:latest

      - name: Clean up unused Docker images
        run: docker image prune -f
